/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medicamentos;

import Empleado.Metodos;
import Farmacia.Procesos_Farmacia;
import Principal.Login;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author JL
 */
public class Ventana_Medicamentos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Medicamentos
     */
    Statement estSQL=Login.estSQL;
    DefaultTableModel modelo=null;
    boolean swCMB=true;
    public Ventana_Medicamentos() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Medicamentos");
        this.setResizable(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        txtIdFarmActual.setVisible(false);
        lblID.setVisible(false);
        
        cerrar();
        String cabecera[]={};
        String datos[][]={};
        swCMB=false;
        genClave();
        cargarComboCiudad();
        genNombreCiudad();
        cargarComboIdFarmacia();
        cargarComboPresentacion();
        swCMB=true;
        modelo=new DefaultTableModel(datos,cabecera);
        tablaMed.setModel(modelo);   
        insertImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMed = new javax.swing.JPanel();
        btnLaboratorio = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMed = new javax.swing.JTable();
        txtIdFarmActual = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPres = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        txtPrec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        txtCiudad = new javax.swing.JTextField();
        cmbIDFarmacia = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarMedPres = new javax.swing.JButton();
        cmbMedicamentos = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAviso = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMoficiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMed.setPreferredSize(new java.awt.Dimension(896, 650));
        panelMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLaboratorio.setBackground(new java.awt.Color(255, 255, 255));
        btnLaboratorio.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ventana.png"))); // NOI18N
        btnLaboratorio.setText("Ventana Laboratorio");
        btnLaboratorio.setPreferredSize(new java.awt.Dimension(213, 55));
        btnLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorioActionPerformed(evt);
            }
        });
        panelMed.add(btnLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 416, 199, -1));

        btnMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        btnMedicamentos.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnMedicamentos.setText("Consultar * Medicamentos");
        btnMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentosActionPerformed(evt);
            }
        });
        panelMed.add(btnMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 416, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar.png"))); // NOI18N
        jButton1.setText("Guardar Registro");
        jButton1.setPreferredSize(new java.awt.Dimension(213, 55));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelMed.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 416, 187, -1));

        tablaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaMed);

        panelMed.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 504, 645, 110));

        txtIdFarmActual.setEditable(false);
        txtIdFarmActual.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        panelMed.add(txtIdFarmActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 376, 342, -1));

        lblID.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lblID.setText("Id. Farmacia Actual: ");
        lblID.setEnabled(false);
        panelMed.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel10.setText("Presentación: ");
        panelMed.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 112, 25));

        txtPres.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        panelMed.add(txtPres, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 342, 342, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel9.setText("Acción Terapéutica: ");
        panelMed.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, -1, 30));

        txtAcc.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        panelMed.add(txtAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 304, 342, -1));

        txtPrec.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        panelMed.add(txtPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 266, 342, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel8.setText("Precio:");
        panelMed.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setText("Cantidad: ");
        panelMed.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 232, -1, 23));

        txtCant.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        panelMed.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 233, 342, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel11.setText("Nombre del Medicamento: ");
        panelMed.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, 24));

        txtNM.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNMActionPerformed(evt);
            }
        });
        panelMed.add(txtNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 199, 342, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel5.setText("Id. Medicamento: ");
        panelMed.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, 24));

        txtIDM.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtIDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMActionPerformed(evt);
            }
        });
        txtIDM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDMKeyTyped(evt);
            }
        });
        panelMed.add(txtIDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 164, 342, -1));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("INGRESAR DATOS DEL MEDICAMENTO: ");
        panelMed.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, 30));

        cmbCiudad.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });
        cmbCiudad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cmbCiudadCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        panelMed.add(cmbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 165, -1));

        txtCiudad.setEditable(false);
        txtCiudad.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        panelMed.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 93, 130, -1));

        cmbIDFarmacia.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbIDFarmacia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIDFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIDFarmaciaActionPerformed(evt);
            }
        });
        panelMed.add(cmbIDFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 93, 171, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("SELECCIONAR FARMACIA: ");
        panelMed.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 66, -1, 21));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("SELECCIONAR CIUDAD:");
        panelMed.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 165, 21));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel1.setText("REGISTRO DE MEDICAMENTOS");
        panelMed.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 27));

        btnConsultarMedPres.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarMedPres.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnConsultarMedPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/stock.png"))); // NOI18N
        btnConsultarMedPres.setText("Consultar Medicamentos");
        btnConsultarMedPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMedPresActionPerformed(evt);
            }
        });
        panelMed.add(btnConsultarMedPres, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        cmbMedicamentos.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbMedicamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMed.add(cmbMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 189, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setText("SELECCIONAR PRESENTACIÓN: ");
        panelMed.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));
        panelMed.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 681, 16));

        lblAviso.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(204, 204, 204));
        lblAviso.setText("Escriba el Id. y luego \"B\" para Buscar.");
        lblAviso.setEnabled(false);
        panelMed.add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 128, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/medicina.png"))); // NOI18N
        panelMed.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 35, -1, 116));

        btnMoficiar.setBackground(new java.awt.Color(255, 255, 255));
        btnMoficiar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnMoficiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar.png"))); // NOI18N
        btnMoficiar.setText("   Modificar");
        btnMoficiar.setPreferredSize(new java.awt.Dimension(193, 55));
        btnMoficiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoficiarActionPerformed(evt);
            }
        });
        panelMed.add(btnMoficiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setPreferredSize(new java.awt.Dimension(183, 55));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelMed.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 193, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMed, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIDFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIDFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIDFarmaciaActionPerformed

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged
        if (evt.getSource()==cmbCiudad && swCMB)
        {
            genNombreCiudad();   
        }
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void txtIDMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDMKeyTyped
        if(!Character.isDigit(evt.getKeyChar())|| txtIDM.getText().length()==10)
        evt.consume();
    }//GEN-LAST:event_txtIDMKeyTyped

    private void txtIDMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDMKeyReleased
        if(evt.getKeyChar()==KeyEvent.VK_B)
        {
            
            txtIdFarmActual.setVisible(true);
            lblID.setVisible(true);
            txtIDM.setBackground(Color.red);
            //////////////////////////////////////
            String sentenciaSQL="select distinct m.id_medicamento,m.nombre,m.cantidad_medic,m.precio,m.accion_terap,m.id_farmacia,p.descripcion from medicamentos m,presentacion p where m.id_medicamento='"+txtIDM.getText().trim()+"' and p.id_medicamento=m.id_medicamento";
            Metodos obj=new Metodos();
            ResultSet rs=obj.consultaDatos(estSQL, sentenciaSQL);

            try{
                rs.next();
                if(rs!=null)
                {
                    txtNM.setText(String.valueOf(rs.getObject(2)));
                    txtAcc.setText(String.valueOf(rs.getObject(5)));
                    txtPrec.setText(String.valueOf(rs.getObject(4)));
                    txtCant.setText(String.valueOf(rs.getObject(3)));
                    txtIdFarmActual.setText(String.valueOf(rs.getObject(6)));
                    txtPres.setText(String.valueOf(rs.getObject(7)));
                }else
                {
                    String sentenciaSQL1="select * from  medicamentos where m.id_medicamento='"+txtIDM.getText().trim()+"'";
                    
                    ResultSet rs1=obj.consultaDatos(estSQL, sentenciaSQL1);
                    rs1.next();
                    txtNM.setText(String.valueOf(rs.getObject(2)));
                    txtAcc.setText(String.valueOf(rs.getObject(5)));
                    txtPrec.setText(String.valueOf(rs.getObject(4)));
                    txtCant.setText(String.valueOf(rs.getObject(3)));
                    txtIdFarmActual.setText(String.valueOf(rs.getObject(6)));
                }
                

            }
            catch(Exception E1)
            {
               JOptionPane.showMessageDialog(null,"El Id seleccionado no existe","Error",JOptionPane.ERROR);
                E1.printStackTrace();
            }

        }
    }//GEN-LAST:event_txtIDMKeyReleased

    private void txtIDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMActionPerformed

    }//GEN-LAST:event_txtIDMActionPerformed

    private void txtNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        BaseDeDatos obj=new BaseDeDatos();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL, transIn);
        String sentenciaSQL="insert into medicamentos values ('"+txtIDM.getText()+"',"+Integer.parseInt(txtCant.getText().trim())+","+Double.parseDouble(txtPrec.getText())+",'"+txtNM.getText().trim()+"','"+txtAcc.getText()+"','"+cmbIDFarmacia.getSelectedItem().toString()+"')";
        if(obj.Ingresar_Datos(estSQL, sentenciaSQL))
        {
            JOptionPane.showMessageDialog(null, "Datos Agregados Exitosamente.");
            
            String sentencia1SQL="insert into presentacion values('"+txtPres.getText()+"','"+txtIDM.getText()+"')";
            obj.Ingresar_Datos(estSQL, sentencia1SQL);
            String transOutOk="COMMIT TRANSACTION";
            obj.transacciones(estSQL, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL, transOutBad);
        }
        
        
        limpiar();
        txtNM.requestFocus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentosActionPerformed
        limpiarTabla(tablaMed);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select * from vista_medic");
        sql.procesarRB(rs, modelo);

        limpiar();
        editarCabecera();
    }//GEN-LAST:event_btnMedicamentosActionPerformed

    private void btnConsultarMedPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMedPresActionPerformed
        limpiarTabla(tablaMed);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select * from vista_Med_Pres where descripcion='"+cmbMedicamentos.getSelectedItem().toString().trim()+"'");
        sql.procesarRB(rs, modelo);
        
        limpiar();
        editarCabecera(); 
    }//GEN-LAST:event_btnConsultarMedPresActionPerformed

    private void btnLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorioActionPerformed
        Ventana_Laboratorio vtn=new Ventana_Laboratorio();
        vtn.setVisible(true);
    }//GEN-LAST:event_btnLaboratorioActionPerformed

    private void btnMoficiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoficiarActionPerformed
        Metodos obj=new Metodos();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL, transIn);
        
        String sentenciaSQL="UPDATE medicamentos SET cantidad_medic="+txtCant.getText().trim()+",precio="+txtPrec.getText().trim()+",nombre='"+txtNM.getText().trim()+"',accion_terap='"+txtAcc.getText().trim()+"',id_farmacia='"+cmbIDFarmacia.getSelectedItem().toString()+"' WHERE id_medicamento='"+txtIDM.getText().trim()+"'";
        
        if(obj.ingresarDatos(estSQL, sentenciaSQL))
        {
            JOptionPane.showMessageDialog(null, "Datos Agregados Exitosamente.");
            String transOutOk="COMMIT TRANSACTION";
            obj.transacciones(estSQL, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL, transOutBad);
        }
        limpiar();
    }//GEN-LAST:event_btnMoficiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String sentenciaSQL="DELETE from medicamentos where id_medicamento='"+txtIDM.getText().trim()+"'";
        Metodos obj=new Metodos();
        obj.ingresarDatos(estSQL, sentenciaSQL);
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbCiudadCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbCiudadCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCiudadCaretPositionChanged

   public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(905,712);
        }
    @Override
    public void paint(Graphics grafico)
    {
        Dimension height = getSize();
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondo1.jpg")); 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
    
    }
   public void limpiar()
    {
        txtIDM.setBackground(Color.white);
        txtIDM.setText("");
        txtPrec.setText("");
        txtCiudad.setText("");
        txtCant.setText("");
        txtAcc.setText("");
        txtPres.setText("");
        txtNM.setText("");
        genClave();
        genNombreCiudad();
        cargarComboPresentacion();
        swCMB=true;
    }
   public void cargarComboPresentacion()
    {
        cmbMedicamentos.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select distinct descripcion from presentacion");
        sql.buscarDatosCombo(rs, cmbMedicamentos);
    }
  public void editarCabecera()
    {
        JTableHeader th; 
        th = tablaMed.getTableHeader(); 
        Font fuente = new Font("Consolas", Font.BOLD, 12); 
        th.setFont(fuente); 
    }
  public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        panelMed.add(Imagen);
        panelMed.repaint();
    }
  public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
   public void genNombreCiudad()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        
        ResultSet rsP=sql.consultarDatos(estSQL, "select nombre_ciudad from ciudad");
        Object valorO;
        try
        {
            rsP.next();
            valorO=rsP.getObject(1);
            if(valorO==null)
            {
                System.out.println("NO HAY VALORES");
            }else
            {
        
                String idFarmacia=cmbCiudad.getSelectedItem().toString().trim();    
                ResultSet rs=sql.consultarDatos(estSQL, "select nombre_ciudad from ciudad where id_ciudad='"+idFarmacia+"'");
                
                try
                {
                    rs.next();
                    txtCiudad.setText(String.valueOf(rs.getObject(1).toString().trim()));
                }catch(java.lang.NullPointerException e)
                {

                }
                catch(Exception e){
                }
            }
        }catch(Exception e)
        {}
        cargarComboIdFarmacia();
    }
     public void cargarComboIdFarmacia()
    {
        cmbIDFarmacia.removeAllItems();
        
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select distinct f.id_farmacia from ciudad c, farmacia f\n" +
        "where c.nombre_ciudad='"+txtCiudad.getText().trim()+"'\n" +
        "and f.id_ciudad=c.id_ciudad");
        sql.buscarDatosCombo(rs, cmbIDFarmacia);
    }
     public void limpiarTabla(JTable tabla)
    {
        while(tabla.getRowCount()>0)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    public void cargarComboCiudad()
    {
        cmbCiudad.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_ciudad from ciudad order by id_ciudad asc");
        sql.buscarDatosCombo(rs, cmbCiudad);
    }
    public void genClave()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String cadeql="select max(id_medicamento) from medicamentos";
        ResultSet rs=sql.consultarUltimoId(estSQL,cadeql);
        Object valorO;
        try
        {   
            rs.next();
            valorO=rs.getObject(1);    
            if(valorO!=null)
            {
                txtIDM.setText(Integer.parseInt(valorO.toString().trim())+1+"");
            }else
            {
                txtIDM.setText(111000+"");
            }
        }catch(Exception e)
        {    
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarMedPres;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLaboratorio;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JButton btnMoficiar;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbIDFarmacia;
    private javax.swing.JComboBox cmbMedicamentos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblID;
    private javax.swing.JPanel panelMed;
    private javax.swing.JTable tablaMed;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtIDM;
    private javax.swing.JTextField txtIdFarmActual;
    private javax.swing.JTextField txtNM;
    private javax.swing.JTextField txtPrec;
    private javax.swing.JTextField txtPres;
    // End of variables declaration//GEN-END:variables
}
