/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmaceutico;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Empleado.*;
import Farmacia.Procesos_Farmacia;
import Principal.Login;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author FRANCISCO
 */
public class Farmaceutico extends javax.swing.JFrame {

    Statement estSQL1=Login.estSQL;
    DefaultTableModel modelo=null;
    public Farmaceutico()
    {
        initComponents();
        
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setTitle("Farmaceutico");
        this.setResizable(false);
     
        cerrar();
        String cabecera[]={};
        String datos[][]={};
        modelo=new DefaultTableModel(datos,cabecera);
        Table.setModel(modelo); 
        cargarComboCiudad();
        limpiarTabla(Table);
        genClave();
        insertImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        panelFarm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId_farmacia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre_FARMACEUTICO = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnFarmaceutico_Enc = new javax.swing.JButton();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setPreferredSize(new java.awt.Dimension(183, 55));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFarm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel1.setText("REGISTRO DE FARMACÉUTICOS");
        panelFarm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 364, 25));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setText("Id. Farmaceutico:");
        panelFarm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, -1));

        txtId_farmacia.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtId_farmacia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtId_farmaciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtId_farmaciaKeyTyped(evt);
            }
        });
        panelFarm.add(txtId_farmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 86, 303, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        panelFarm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        txtNombre_FARMACEUTICO.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtNombre_FARMACEUTICO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre_FARMACEUTICOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_FARMACEUTICOKeyTyped(evt);
            }
        });
        panelFarm.add(txtNombre_FARMACEUTICO, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 126, 303, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar Registro");
        btnGuardar.setPreferredSize(new java.awt.Dimension(211, 55));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelFarm.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 203, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnBuscar.setText("Mostrar Farmacéuticos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelFarm.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new java.awt.Dimension(211, 55));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelFarm.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 203, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Escriba el Id. y luego B para Buscar.");
        jLabel5.setEnabled(false);
        panelFarm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 243, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        panelFarm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 620, 138));

        btnFarmaceutico_Enc.setBackground(new java.awt.Color(255, 255, 255));
        btnFarmaceutico_Enc.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnFarmaceutico_Enc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/personal.png"))); // NOI18N
        btnFarmaceutico_Enc.setText("Farmacéutico Encargado");
        btnFarmaceutico_Enc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaceutico_EncActionPerformed(evt);
            }
        });
        panelFarm.add(btnFarmaceutico_Enc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        cmbCiudad.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFarm.add(cmbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 211, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        jLabel6.setText("SELECCIONAR CIUDAD:");
        panelFarm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 147, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelFarm.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 10, 138));
        panelFarm.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 700, 10));
        panelFarm.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 880, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doctor-icon.png"))); // NOI18N
        panelFarm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 19, 127, 129));

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setPreferredSize(new java.awt.Dimension(183, 55));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        panelFarm.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFarm, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFarm, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        Metodos obj=new Metodos();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL1, transIn);
        
        String sentenciaSQL="UPDATE farmaceutico SET nombre_farmaceutico='"+txtNombre_FARMACEUTICO.getText().trim()+"' WHERE id_farmaceutico='"+txtId_farmacia.getText().trim()+"'";
        
        if(obj.ingresarDatos(estSQL1, sentenciaSQL))
        {
                JOptionPane.showMessageDialog(null, "Datos Modificados Exitosamente.");
            String transOutOk="COMMIT TRANSACTION";
            obj.transacciones(estSQL1, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL1, transOutBad);
        }
        txtNombre_FARMACEUTICO.setText("");
        txtId_farmacia.requestFocus();
        limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTabla(Table);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL1, "select * from farmaceutico");
        sql.procesarRB(rs, modelo);
        editarCabecera();    
        limpiar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Metodos obj=new Metodos();        
        
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL1, transIn);
        
        String sentenciaSQL="Insert into farmaceutico values('"+txtId_farmacia.getText().trim()+"','"+txtNombre_FARMACEUTICO.getText().trim()+"')";
        if(obj.ingresarDatos(estSQL1, sentenciaSQL))
        {
            
            JOptionPane.showMessageDialog(null, "Datos Agregados Exitosamente.");
            String transOutOk="COMMIT TRANSACTION";
            obj.transacciones(estSQL1, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL1, transOutBad);
        }
        
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombre_FARMACEUTICOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_FARMACEUTICOKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_txtNombre_FARMACEUTICOKeyTyped

    private void txtNombre_FARMACEUTICOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_FARMACEUTICOKeyReleased

    }//GEN-LAST:event_txtNombre_FARMACEUTICOKeyReleased

    private void txtId_farmaciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId_farmaciaKeyTyped
        if(!Character.isDigit(evt.getKeyChar())|| txtId_farmacia.getText().length()==10)
        evt.consume();
    }//GEN-LAST:event_txtId_farmaciaKeyTyped

    private void txtId_farmaciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId_farmaciaKeyReleased
        if(evt.getKeyChar()==KeyEvent.VK_B)
        {
            txtId_farmacia.setBackground(Color.red);
            //////////////////////////////////////
            String sentenciaSQL="select *from farmaceutico where id_farmaceutico='"+txtId_farmacia.getText()+"'";
            Metodos obj=new Metodos();
            ResultSet rs=obj.consultaDatos(estSQL1, sentenciaSQL);

            try
            {
                rs.next();
                txtNombre_FARMACEUTICO.setText(String.valueOf(rs.getObject(2)));
            }
            catch(Exception E1)
            {
                JOptionPane.showMessageDialog(null,"El id seleccionado no existe");
                E1.printStackTrace();
            }

        }
    }//GEN-LAST:event_txtId_farmaciaKeyReleased

    private void btnFarmaceutico_EncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaceutico_EncActionPerformed
        limpiarTabla(Table);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL1, "select distinct f.id_farmaceutico,nombre_farmaceutico,c.id_ciudad,nombre_ciudad\n" +
"from farmacia, farmaceutico f,ciudad c\n" +
"where f.id_farmaceutico=farmacia.id_farmaceutico\n" +
"and c.id_ciudad=farmacia.id_ciudad\n" +
"and nombre_ciudad='"+cmbCiudad.getSelectedItem().toString().trim()+"'");
        sql.procesarRB(rs, modelo);
        editarCabecera(); 
        limpiar();
    }//GEN-LAST:event_btnFarmaceutico_EncActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        Metodos obj=new Metodos();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL1, transIn);
        
        String sentenciaSQL="DELETE from farmaceutico where id_farmaceutico='"+txtId_farmacia.getText().trim()+"'";
        
        if(obj.ingresarDatos(estSQL1, sentenciaSQL))
        {
                JOptionPane.showMessageDialog(null, "Datos Eliminados Exitosamente.");
                String transOutOk="COMMIT TRANSACTION";
                obj.transacciones(estSQL1, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL1, transOutBad);
        }
        limpiar();       
    }//GEN-LAST:event_btnEliminar1ActionPerformed
    public void limpiar()
    {
        txtId_farmacia.setBackground(Color.white);
        txtId_farmacia.setText("");
        txtNombre_FARMACEUTICO.setText("");
        txtId_farmacia.requestFocus();
        genClave();
        cargarComboCiudad();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnFarmaceutico_Enc;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelFarm;
    private javax.swing.JTextField txtId_farmacia;
    private javax.swing.JTextField txtNombre_FARMACEUTICO;
    // End of variables declaration//GEN-END:variables
    
    public void cargarComboCiudad()
    {
        cmbCiudad.removeAllItems();
        ResultSet rs;
        Metodos obj=new Metodos();
        rs=obj.consultaDatos(estSQL1,"SELECT nombre_ciudad FROM ciudad");
        obj.procesarRSCombo(rs, cmbCiudad);

    }
 public void limpiarTabla(JTable tabla)
    {
        while(tabla.getRowCount()>0)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
 
  public void genClave()
    {
        Metodos sql=new Metodos();
        String cadeql="select max(id_farmaceutico) from farmaceutico";
        ResultSet rs=sql.consultarUltimoId(estSQL1,cadeql);
        Object valorO;
        try
        {   
            rs.next();
            valorO=rs.getObject(1);    
            if(valorO!=null)
            {
                txtId_farmacia.setText(Integer.parseInt(valorO.toString().trim())+1+"");
            }else
            {
                txtId_farmacia.setText(555000+"");
            }
        }catch(Exception e)
        {    
        }
        
    }
   public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(915,470);
        }
    @Override
    public void paint(Graphics grafico)
    {
        Dimension height = getSize();
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondo1.jpg")); 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
    }
  public void editarCabecera()
    {
        JTableHeader th; 
        th = Table.getTableHeader(); 
        Font fuente = new Font("Consolas", Font.BOLD, 12); 
        th.setFont(fuente); 
    }
  public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        panelFarm.add(Imagen);
        panelFarm.repaint();
    }
  public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

}

