/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia;

import Empleado.Metodos;
import Principal.Login;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author JL
 */

public class Ventana_Farmacia extends javax.swing.JFrame {
    public static Statement estSQL=Login.estSQL;
    DefaultTableModel modelo=null;
    boolean swCMB=true;

    /**
     * Creates new form Ventana_Farmacia
     */
    public Ventana_Farmacia() 
    {
        initComponents();
        insertImage();
        
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setTitle("Farmacia");
        this.setResizable(false);
        cerrar();
        String cabecera[]={};
        String datos[][]={};
        modelo=new DefaultTableModel(datos,cabecera);
        TablaFarmacia.setModel(modelo); 
        swCMB=false;
        genClave();
        cargarComboCiudad();
        cargarComboFarmaceutico();
        cargarComboIdFarmacia();
        cargarComboMedic();
        genNombreCiudad();
        genNombreFarmaceutico();
        swCMB=true;
         txtActual.setVisible(false);
        labell.setVisible(false);
         txtActual2.setVisible(false);
        labell2.setVisible(false);
       
    }
    public void conexionBD()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        estSQL=sql.conexion("sa", "sa.1","Farmacia2", "JOEL-PC\\SQLSERVER2");
    }
    public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdFarmacia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbFarmacéutico = new javax.swing.JComboBox();
        txtNombreFarmaceutico = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultarPersonal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaFarmacia = new javax.swing.JTable();
        btnConsultarStock = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnConsultarFarmacias = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbIdFarmPersonal = new javax.swing.JComboBox();
        labell = new javax.swing.JLabel();
        txtActual = new javax.swing.JTextField();
        labell2 = new javax.swing.JLabel();
        txtActual2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnMoficiar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbMedic = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setPreferredSize(new java.awt.Dimension(711, 560));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel9.setText("FARMACIA");

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel10.setText("INGRESAR: ");

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel11.setText("Id. Farmacia: ");

        txtIdFarmacia.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtIdFarmacia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdFarmaciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdFarmaciaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("SELECCIONAR CIUDAD: ");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel2.setText("Id. Ciudad: ");

        cmbCiudad.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel3.setText("Nombre Ciudad: ");

        txtNombreCiudad.setEditable(false);
        txtNombreCiudad.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("SELECCIONAR FARMACÉUTICO: ");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel5.setText("Id. Farmacéutico: ");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        jLabel6.setText("Nombre Farmacéutico: ");

        cmbFarmacéutico.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbFarmacéutico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFarmacéutico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFarmacéuticoItemStateChanged(evt);
            }
        });
        cmbFarmacéutico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbFarmacéuticoFocusLost(evt);
            }
        });

        txtNombreFarmaceutico.setEditable(false);
        txtNombreFarmaceutico.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtNombreFarmaceutico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFarmaceuticoFocusLost(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar.png"))); // NOI18N
        btnGuardar.setText("     Guardar Registro");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnConsultarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarPersonal.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnConsultarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/personal.png"))); // NOI18N
        btnConsultarPersonal.setText("Consultar Personal ");
        btnConsultarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPersonalActionPerformed(evt);
            }
        });

        TablaFarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaFarmacia);

        btnConsultarStock.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarStock.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnConsultarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/stock.png"))); // NOI18N
        btnConsultarStock.setText("Consultar Stock");
        btnConsultarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarStockActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/spreadfirefox_favicon.png"))); // NOI18N

        btnConsultarFarmacias.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarFarmacias.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnConsultarFarmacias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/farmacias.png"))); // NOI18N
        btnConsultarFarmacias.setText("Consultar Farmacias");
        btnConsultarFarmacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFarmaciasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel12.setText("SELECCIONAR ID. FARMACIA");

        cmbIdFarmPersonal.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbIdFarmPersonal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labell.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        labell.setText("Ciudad actual:");
        labell.setEnabled(false);

        txtActual.setEditable(false);
        txtActual.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N

        labell2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        labell2.setText("Farmacèutico actual:");
        labell2.setEnabled(false);

        txtActual2.setEditable(false);
        txtActual2.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Escriba el Id. y luego \"B\" para Buscar.");
        jLabel13.setEnabled(false);

        btnMoficiar.setBackground(new java.awt.Color(255, 255, 255));
        btnMoficiar.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnMoficiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar.png"))); // NOI18N
        btnMoficiar.setText("   Modificar");
        btnMoficiar.setPreferredSize(new java.awt.Dimension(193, 55));
        btnMoficiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoficiarActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar1.setText("     Eliminar");
        btnEliminar1.setPreferredSize(new java.awt.Dimension(183, 55));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel7.setText("SELECCIONAR MEDICAMENTO");

        cmbMedic.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        cmbMedic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jSeparator4)
                            .addComponent(jLabel4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelMainLayout.createSequentialGroup()
                                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(labell))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbCiudad, 0, 312, Short.MAX_VALUE)
                                            .addComponent(txtNombreCiudad)
                                            .addComponent(txtActual)))
                                    .addGroup(PanelMainLayout.createSequentialGroup()
                                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(133, 133, 133)))
                                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txtIdFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(labell2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbFarmacéutico, 0, 315, Short.MAX_VALUE)
                                    .addComponent(txtNombreFarmaceutico)
                                    .addComponent(txtActual2))
                                .addGap(77, 77, 77))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarFarmacias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoficiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbMedic, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnConsultarPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(cmbIdFarmPersonal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labell)
                            .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarStock)))
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbFarmacéutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labell2)
                            .addComponent(txtActual2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNombreFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnConsultarFarmacias)
                            .addComponent(btnMoficiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbIdFarmPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnConsultarPersonal)
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String idFarmacia=txtIdFarmacia.getText();
        String idCiudad=cmbCiudad.getSelectedItem().toString();
        String idFarmaceutico=cmbFarmacéutico.getSelectedItem().toString().trim();
        
        String transIn="BEGIN TRANSACTION";
        sql.transacciones(estSQL, transIn);
        
        String sentenciaSQL=("insert into farmacia values ('"+idFarmacia+"','"+idFarmaceutico+"','"+idCiudad+"')");
        if(sql.ingresarDatos(estSQL, sentenciaSQL))
        {

        
            JOptionPane.showMessageDialog(null, "Datos Agregados Exitosamente.");
            String transOutOk="COMMIT TRANSACTION";
            sql.transacciones(estSQL, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            sql.transacciones(estSQL, transOutBad);
        }
        
        limpiar();
      
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged
     
        
        if (evt.getSource()==cmbCiudad && swCMB) 
        {
            genNombreCiudad();
        }
     
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void cmbFarmacéuticoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFarmacéuticoItemStateChanged
        if (evt.getSource()==cmbFarmacéutico && swCMB) 
        {
            genNombreFarmaceutico();
        }
    }//GEN-LAST:event_cmbFarmacéuticoItemStateChanged

    private void btnConsultarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPersonalActionPerformed
        limpiarTabla(TablaFarmacia);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select e.id_empleado,e.nombres_empleado,e.apellidos_empleado,c.nombre_ciudad,f.id_farmacia from empleado e,farmacia f,ciudad c\n" +
        " where f.id_farmacia='"+cmbIdFarmPersonal.getSelectedItem().toString().trim()+"'\n" +
        " and f.id_ciudad=c.id_ciudad\n" +
        " and e.id_farmacia=f.id_farmacia");
        sql.procesarRB(rs, modelo);
        modificarColumnaTabla();
        limpiar();
        editarCabecera(); 
    }//GEN-LAST:event_btnConsultarPersonalActionPerformed

    private void btnConsultarFarmaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFarmaciasActionPerformed
        limpiarTabla(TablaFarmacia);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select * from vista_farmacias");
        sql.procesarRB(rs, modelo);
        modificarColumnaTabla();
        limpiar();
        editarCabecera();        
    }//GEN-LAST:event_btnConsultarFarmaciasActionPerformed

    private void btnConsultarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarStockActionPerformed
        limpiarTabla(TablaFarmacia);
        Procesos_Farmacia sql=new Procesos_Farmacia();
        //ResultSet rs=sql.consultarDatos(estSQL, "Select * from farmacia");
        ResultSet rs=sql.consultarDatos(estSQL, "select * from vista_stock where id_farmacia='"+cmbMedic.getSelectedItem().toString().trim()+"'");
        sql.procesarRB(rs, modelo);
        modificarColumnaTabla();
        limpiar();
        editarCabecera(); 
    }//GEN-LAST:event_btnConsultarStockActionPerformed

    private void cmbFarmacéuticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbFarmacéuticoFocusLost
        
    }//GEN-LAST:event_cmbFarmacéuticoFocusLost

    private void txtNombreFarmaceuticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFarmaceuticoFocusLost
        
    }//GEN-LAST:event_txtNombreFarmaceuticoFocusLost

    private void btnMoficiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoficiarActionPerformed
 
        txtActual.setVisible(false);
        labell.setVisible(false);
        txtActual2.setVisible(false);
        labell2.setVisible(false);
         Procesos_Farmacia obj=new Procesos_Farmacia();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL, transIn);         
        
        String sentenciaSQL="UPDATE farmacia SET id_farmaceutico='"+cmbFarmacéutico.getSelectedItem().toString()+"',id_ciudad='"+cmbCiudad.getSelectedItem().toString()+"'WHERE id_farmacia='"+txtIdFarmacia.getText().trim()+"'";
       
        if(obj.ingresarDatos(estSQL, sentenciaSQL))
        {
               JOptionPane.showMessageDialog(null, "Datos Modificados Exitosamente.");
                String transOutOk="COMMIT TRANSACTION";
                obj.transacciones(estSQL, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL, transOutBad);
        }
        limpiar();
    }//GEN-LAST:event_btnMoficiarActionPerformed

    private void txtIdFarmaciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFarmaciaKeyReleased
          if(evt.getKeyChar()==KeyEvent.VK_B)
        {
            txtActual.setVisible(true);
        labell.setVisible(true);
         txtActual2.setVisible(true);
        labell2.setVisible(true);
            txtIdFarmacia.setBackground(Color.red);
            //////////////////////////////////////
            String sentenciaSQL="select *from farmacia where id_farmacia='"+txtIdFarmacia.getText()+"'";
            Procesos_Farmacia obj=new Procesos_Farmacia();
            ResultSet rs=obj.consultarDatos(estSQL, sentenciaSQL);

            try{
                
                rs.next();
                txtActual.setText(String.valueOf(rs.getObject(3)));
                txtActual2.setText(String.valueOf(rs.getObject(2)));
               
            }
            catch(Exception E1)
            {
                JOptionPane.showMessageDialog(null,"El id seleccionado no existe");
                E1.printStackTrace();
            }

        }
    }//GEN-LAST:event_txtIdFarmaciaKeyReleased

    private void txtIdFarmaciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFarmaciaKeyTyped
        if(!Character.isDigit(evt.getKeyChar())|| txtIdFarmacia.getText().length()==10)
        evt.consume();
    }//GEN-LAST:event_txtIdFarmaciaKeyTyped

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        Metodos obj=new Metodos();
        String transIn="BEGIN TRANSACTION";
        obj.transacciones(estSQL, transIn);
        
        String sentenciaSQL="DELETE from farmacia where id_farmacia='"+txtIdFarmacia.getText().trim()+"'";

        if(obj.ingresarDatos(estSQL, sentenciaSQL))
        {
                JOptionPane.showMessageDialog(null, "Datos Eliminados Exitosamente.");
                String transOutOk="COMMIT TRANSACTION";
                obj.transacciones(estSQL, transOutOk);
        }else
        {
            String transOutBad="ROLLBACK TRANSACTION";
            obj.transacciones(estSQL, transOutBad);
        }
        limpiar(); 
    }//GEN-LAST:event_btnEliminar1ActionPerformed
    public void modificarColumnaTabla()
    {
        //TableColumnModel columnModel = TablaFarmacia.getColumnModel();
        //columnModel.getColumn(2).setPreferredWidth(100);
    }
    public void editarCabecera()
    {
        JTableHeader th; 
        th = TablaFarmacia.getTableHeader(); 
        Font fuente = new Font("Consolas", Font.BOLD, 12); 
        th.setFont(fuente); 
    }
    public void genClave()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String cadeql="select max(id_farmacia) from farmacia";
        ResultSet rs=sql.consultarUltimoId(estSQL,cadeql);
        Object valorO;
        try
        {   
            rs.next();
            valorO=rs.getObject(1);    
            if(valorO!=null)
            {
                txtIdFarmacia.setText(Integer.parseInt(valorO.toString().trim())+1+"");
            }else
            {
                txtIdFarmacia.setText(666000+"");
            }
        }catch(Exception e)
        {    
        }   
    }
    public int valorBand1()
    {
        int valor=0;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String cadeql="select count(*) from farmaceutico fc, ciudad c, farmacia f\n" +
        "where fc.id_farmaceutico=f.id_farmaceutico and c.id_ciudad=f.id_ciudad and f.id_ciudad='"+cmbCiudad.getSelectedItem().toString().trim()+"'";
        ResultSet rs=sql.consultarUltimoId(estSQL,cadeql);
       
        Object valorO,valor1;
        try
        {   
            rs.next();
            
            valorO=rs.getObject(1);    
            valor=Integer.parseInt(valorO.toString().trim());
        }catch(Exception e)
        {    
        }   
        return valor;
    }
    public int valorBand2()
    {
        int valor=0;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        String cadeql="select count(*) from farmaceutico fc, ciudad c, farmacia f\n" +
        "where fc.id_farmaceutico=f.id_farmaceutico and c.id_ciudad=f.id_ciudad and fc.nombre_farmaceutico='"+txtNombreFarmaceutico.getText().trim()+"'";
        
        ResultSet rs=sql.consultarUltimoId(estSQL,cadeql);
       
        Object valorO;
        try
        {   
            rs.next();
            
            valorO=rs.getObject(1);    
            valor=Integer.parseInt(valorO.toString().trim());
        }catch(Exception e)
        {    
        }   
        return valor;
    }
    public void limpiarTabla(JTable tabla)
    {
        while(tabla.getRowCount()>0)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    public void limpiar()
    {
        txtIdFarmacia.setText("");
        txtIdFarmacia.setBackground(Color.white);
        txtIdFarmacia.requestFocus();
        genClave();
        cargarComboIdFarmacia();
        swCMB=true;
    }
    public void cargarComboIdFarmacia()
    {
        cmbIdFarmPersonal.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_farmacia from farmacia order by id_farmacia asc");
        sql.buscarDatosCombo(rs, cmbIdFarmPersonal);
    }
    public void cargarComboCiudad()
    {
        cmbCiudad.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_ciudad from ciudad order by id_ciudad asc");
        sql.buscarDatosCombo(rs, cmbCiudad);
    }
    public void cargarComboFarmaceutico()
    {
        cmbFarmacéutico.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_farmaceutico from farmaceutico order by id_farmaceutico asc");
        sql.buscarDatosCombo(rs, cmbFarmacéutico);
    }
    public void cargarComboMedic()
    {
        cmbMedic.removeAllItems();
        swCMB=false;
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rs=sql.consultarDatos(estSQL, "select distinct id_farmacia from vista_stock order by id_farmacia asc");
        sql.buscarDatosCombo(rs, cmbMedic);
    }
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        PanelMain.add(Imagen);
        PanelMain.repaint();
    }
    public void genNombreCiudad()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        
        ResultSet rsP=sql.consultarDatos(estSQL, "select nombre_ciudad from ciudad");
        Object valorO;
        try
        {
            rsP.next();
            valorO=rsP.getObject(1);
            if(valorO==null)
            {
                System.out.println("NO HAY VALORES");
            }else
            {
        
                String idFarmacia=cmbCiudad.getSelectedItem().toString();    
                ResultSet rs=sql.consultarDatos(estSQL, "select nombre_ciudad from ciudad where id_ciudad='"+idFarmacia+"'");
                try
                {
                    rs.next();
                    txtNombreCiudad.setText(String.valueOf(rs.getObject(1)));
                }catch(java.lang.NullPointerException e)
                {

                }
                catch(Exception e){
                }
            }
        }catch(Exception e)
        {}
    }
    public void genNombreFarmaceutico()
    {
        Procesos_Farmacia sql=new Procesos_Farmacia();
        ResultSet rsP=sql.consultarDatos(estSQL, "select nombre_farmaceutico from farmaceutico ");
        Object valorO;
        try
        {
            rsP.next();
            valorO=rsP.getObject(1);
            if(valorO==null)
            {
                System.out.println("NO HAY VALORES");
            }else
            {
                try
                {
                    String idFarmaceutico=cmbFarmacéutico.getSelectedItem().toString();
                    ResultSet rs=sql.consultarDatos(estSQL, "select nombre_farmaceutico from farmaceutico where id_farmaceutico='"+idFarmaceutico+"'");    
                    rs.next();
                    txtNombreFarmaceutico.setText(String.valueOf(rs.getObject(1)));
                }catch(java.lang.NullPointerException e)
                {

                }catch(Exception e){}
                }
        }catch(Exception e)
        {}
    }
    
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(915,725);
        }
    @Override
    public void paint(Graphics grafico)
    {
        Dimension height = getSize();
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondo1.jpg")); 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JTable TablaFarmacia;
    private javax.swing.JButton btnConsultarFarmacias;
    private javax.swing.JButton btnConsultarPersonal;
    private javax.swing.JButton btnConsultarStock;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMoficiar;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbFarmacéutico;
    private javax.swing.JComboBox cmbIdFarmPersonal;
    private javax.swing.JComboBox cmbMedic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labell;
    private javax.swing.JLabel labell2;
    private javax.swing.JTextField txtActual;
    private javax.swing.JTextField txtActual2;
    private javax.swing.JTextField txtIdFarmacia;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtNombreFarmaceutico;
    // End of variables declaration//GEN-END:variables
}
